# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI build

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'pom.xml'
      - '.github/workflows/maven.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'pom.xml'
      - '.github/workflows/maven.yml'
  schedule:
    - cron: "30 3 * * 0"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Maven build
        run: ./mvnw -B -U clean install
